// docs/mockup/components/Hero.tsx

import React from 'react';
import { Link } from 'react-router-dom';

const Hero: React.FC = () => {
  return (
    <section className="relative pt-40 pb-20 md:pt-48 md:pb-32 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-rose-100/80 to-brand-light">
      <div className="container mx-auto px-4">
        <div className="grid md:grid-cols-2 gap-12 items-center">
          {/* Text Content */}
          <div className="text-center md:text-left">
            <div className="inline-block bg-white/60 rounded-full px-4 py-1.5 mb-4 shadow-sm">
              <p className="text-sm text-[#5A0D29] font-medium">Online Verzuimadvies</p>
            </div>
            <h1 className="font-serif text-4xl md:text-6xl font-bold text-[#5A0D29] leading-tight">
              Professioneel advies binnen handbereik
            </h1>
            <p className="mt-6 text-lg text-brand-text max-w-xl mx-auto md:mx-0">
              Direct antwoord op al uw vragen over verzuim, re-integratie en arbeidsgerelateerde zaken. Efficiënt, betrouwbaar en altijd beschikbaar.
            </p>
            <div className="mt-10 flex flex-col sm:flex-row justify-center md:justify-start items-center gap-4">
              <Link to="/chat" className="bg-[#771138] text-white font-bold py-3 px-8 rounded-full shadow-lg hover:bg-[#5A0D29] transition-all w-full sm:w-auto">
                Probeer DOBbie
              </Link>
              <a href="#waarom" className="bg-[#E9B046] text-black font-bold py-3 px-8 rounded-full shadow-lg hover:bg-[#5A0D29] hover:text-white transition-all w-full sm:w-auto">
                Meer Informatie
              </a>
            </div>
          </div>
          
          {/* Smartphone Mockup */}
          <div className="relative w-full flex justify-center -mt-10 md:mt-0 group">
            
            <div className="w-60 md:w-72 h-[30rem] md:h-[34rem] bg-slate-900 rounded-[3rem] p-3 shadow-2xl shadow-black/30 transform -rotate-2 group-hover:rotate-0 group-hover:scale-105 transition-transform duration-300 ease-in-out">
              <div className="bg-white h-full w-full rounded-[2.5rem] overflow-hidden">
                <video 
                  src="/video/demo-dobbie.mp4"
                  autoPlay 
                  loop 
                  muted 
                  playsInline
                  className="w-full h-full object-cover"
                >
                  Your browser does not support the video tag.
                </video>
              </div>
            </div>
          </div>

        </div>
      </div>
    </section>
  );
};

export default Hero;

// .svelte-backup/components/landing/Hero.svelte
<!-- Hero Section -->
<section class="pt-24 pb-16 md:pt-32 md:pb-24 bg-cream relative">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex flex-col md:flex-row items-center">
            <div class="md:w-1/2 mb-10 md:mb-0">
                <h1 class="font-serif text-h1 font-bold text-bordeaux leading-tight">DOBbie - Online Verzuimadvies: Professioneel advies binnen handbereik</h1>
                <p class="mt-4 text-body text-gray-dark">Direct antwoord op al uw vragen over verzuim, re-integratie en arbeidsgerelateerde zaken. Efficiënt, betrouwbaar en altijd beschikbaar.</p>
                <div class="mt-8 flex flex-col sm:flex-row">
                    <a href="/login" class="bg-bordeaux text-white font-bold text-button px-6 py-3 rounded-button shadow-card hover:bg-bordeaux-hover transition-colors duration-300 text-center">Start direct</a>
                    <a href="#how-it-works" class="mt-4 sm:mt-0 sm:ml-4 text-bordeaux border-2 border-bordeaux px-6 py-3 rounded-button hover:bg-bordeaux hover:text-white transition-colors duration-300 text-center font-bold text-button">Meer informatie</a>
                </div>
            </div>
            <div class="md:w-1/2 md:pl-10">
                <div class="bg-white p-4 rounded-card shadow-chat max-w-md mx-auto">
                    <div class="flex items-center border-b border-gray-light pb-4">
                        <div class="w-10 h-10 rounded-full bg-cream flex items-center justify-center">
                            <svg class="h-6 w-6 text-bordeaux" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z" clip-rule="evenodd"></path>
                            </svg>
                        </div>
                        <div class="ml-3">
                            <p class="text-lg font-semibold text-black">DOBbie</p>
                            <p class="text-small text-gray-dark">Online • Direct beschikbaar</p>
                        </div>
                    </div>
                    <div class="py-4 h-64 overflow-y-auto">
                        <div class="flex mb-4">
                            <div class="bg-cream rounded-[16px_16px_16px_4px] py-2 px-4 max-w-[80%]">
                                <p class="text-gray-dark">Goedendag! Ik ben DOBbie uw digitale verzuimbuddy. Hoe kan ik u vandaag helpen?</p>
                            </div>
                        </div>
                        <div class="flex justify-end mb-4">
                            <div class="bg-bordeaux text-white rounded-[16px_16px_4px_16px] py-2 px-4 max-w-[80%]">
                                <p class="text-white">Een medewerker is al 3 weken ziek. Wat moet ik doen?</p>
                            </div>
                        </div>
                        <div class="flex mb-4">
                            <div class="bg-cream rounded-[16px_16px_16px_4px] py-2 px-4 max-w-[80%]">
                                <p class="text-gray-dark">Bij 3 weken verzuim is het belangrijk om:</p>
                                <ul class="list-disc pl-5 mt-2 space-y-1 text-gray-dark">
                                    <li>Een plan van aanpak op te stellen</li>
                                    <li>Contact te houden met de medewerker</li>
                                    <li>De bedrijfsarts in te schakelen</li>
                                </ul>
                                <p class="mt-2 text-gray-dark">Ik kan u helpen met de specifieke stappen volgens de Wet Verbetering Poortwachter.</p>
                            </div>
                        </div>
                    </div>
                    <div class="border-t border-gray-light pt-4">
                        <div class="relative">
                            <input type="text" placeholder="Stel uw vraag..." class="w-full border border-gray-light rounded-input py-3 px-4 pr-12 focus:outline-none focus:ring-2 focus:ring-bordeaux focus:border-transparent">
                            <button class="absolute right-2 top-1/2 transform -translate-y-1/2 bg-bordeaux text-white rounded-full p-2 hover:bg-bordeaux-hover transition-colors">
                                <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"></path>
                                </svg>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<style>
    :global(html) {
        scroll-behavior: smooth;
    }
</style>
