// app/auth/callback/page.tsx
'use client';

import { Suspense, useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';

function AuthCallbackContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const handleCallback = async () => {
      const supabase = createClient();

      // Get parameters from URL
      const code = searchParams.get('code');
      const token = searchParams.get('token') || searchParams.get('token_hash');
      const type = searchParams.get('type');
      const next = searchParams.get('next') || searchParams.get('redirect');

      console.log('Auth callback params:', { code, token: token?.substring(0, 20) + '...', type, next });

      try {
        // Handle code-based flow (OAuth, etc.)
        if (code) {
          const { error } = await supabase.auth.exchangeCodeForSession(code);

          if (error) {
            console.error('Auth callback error:', error);
            setError('Authenticatie mislukt. Probeer opnieuw in te loggen.');
            setTimeout(() => router.push('/login'), 3000);
            return;
          }

          // For password recovery, redirect to reset-password page
          if (type === 'recovery') {
            router.push('/reset-password');
            return;
          }

          // Success - redirect to destination or default to /chat
          router.push(next || '/chat');
          return;
        }

        // Handle token-based flow (email confirmation, magic links)
        if (token && type) {
          console.log('Attempting verifyOtp with token type:', type);

          const { data, error } = await supabase.auth.verifyOtp({
            token_hash: token,
            type: type as 'signup' | 'recovery' | 'email',
          });

          if (error) {
            console.error('Token verification error:', error.message, error);
            setError(`Verificatie mislukt: ${error.message}`);
            setTimeout(() => router.push('/login'), 3000);
            return;
          }

          console.log('verifyOtp success:', data?.user?.email);

          // For password recovery, redirect to reset-password page
          if (type === 'recovery') {
            router.push('/reset-password');
            return;
          }

          // Success - redirect to destination or default to /chat
          router.push(next || '/chat');
          return;
        }

        // No valid parameters found
        console.warn('No valid auth parameters found in callback');
        router.push('/login');
      } catch (error) {
        console.error('Unexpected error in auth callback:', error);
        setError('Er ging iets mis tijdens authenticatie.');
        setTimeout(() => router.push('/login'), 3000);
      }
    };

    handleCallback();
  }, [router, searchParams]);

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <div className="max-w-md w-full space-y-8 p-8">
        <div className="text-center">
          {error ? (
            <>
              <div className="mx-auto h-12 w-12 text-red-500 mb-4">
                <svg
                  className="h-full w-full"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
                  />
                </svg>
              </div>
              <h2 className="text-2xl font-bold text-gray-900 mb-2">
                Authenticatie mislukt
              </h2>
              <p className="text-gray-600">{error}</p>
              <p className="text-sm text-gray-500 mt-2">
                Je wordt doorgestuurd naar de login pagina...
              </p>
            </>
          ) : (
            <>
              <div className="mx-auto h-12 w-12 text-blue-500 mb-4 animate-spin">
                <svg
                  className="h-full w-full"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <circle
                    className="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    strokeWidth="4"
                  />
                  <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                  />
                </svg>
              </div>
              <h2 className="text-2xl font-bold text-gray-900 mb-2">
                Account verifiëren...
              </h2>
              <p className="text-gray-600">
                Een moment geduld terwijl we je account verifiëren.
              </p>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

function LoadingFallback() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <div className="max-w-md w-full space-y-8 p-8">
        <div className="text-center">
          <div className="mx-auto h-12 w-12 text-blue-500 mb-4 animate-spin">
            <svg className="h-full w-full" fill="none" viewBox="0 0 24 24">
              <circle
                className="opacity-25"
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                strokeWidth="4"
              />
              <path
                className="opacity-75"
                fill="currentColor"
                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
              />
            </svg>
          </div>
          <h2 className="text-2xl font-bold text-gray-900 mb-2">Laden...</h2>
        </div>
      </div>
    </div>
  );
}

export default function AuthCallbackPage() {
  return (
    <Suspense fallback={<LoadingFallback />}>
      <AuthCallbackContent />
    </Suspense>
  );
}

// .svelte-backup/routes/auth/callback/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { page } from '$app/stores';
  import { supabase } from '$lib/supabase/client';
  import { updateAuthState } from '$lib/stores/userStore';
  import { toast } from 'svelte-sonner';

  let isLoading = true;
  let error = '';
  let success = false;

  onMount(async () => {
    try {
      // Get the code, token and type from URL parameters
      const code = $page.url.searchParams.get('code');
      const token = $page.url.searchParams.get('token');
      const type = $page.url.searchParams.get('type');
      
      if (!code && !token) {
        throw new Error('Geen bevestigingscode of token gevonden in de URL.');
      }

      let data, error;

      if (token && type) {
        // Handle token-based verification (email confirmation)
        console.log('Processing token-based verification:', { token: token.substring(0, 10) + '...', type });
        
        const result = await supabase.auth.verifyOtp({
          token_hash: token,
          type: type as any
        });
        
        data = result.data;
        error = result.error;
      } else if (code) {
        // Handle code-based verification (PKCE flow)
        console.log('Processing code-based verification:', { code: code.substring(0, 10) + '...', type });
        
        const result = await supabase.auth.exchangeCodeForSession(code);
        data = result.data;
        error = result.error;
      }

      if (error) {
        console.error('Code exchange error:', error);
        throw new Error('Ongeldige of verlopen bevestigingslink.');
      }

      if (!data || !data.session) {
        throw new Error('Geen sessie ontvangen na bevestiging.');
      }

      console.log('Email confirmation successful, user:', data.session.user.email);

      // Update auth state
      updateAuthState(data.session);

      success = true;
      
      // Show success message
      toast.success('E-mailadres succesvol bevestigd! Je wordt doorgestuurd...');

      // Redirect to chat after successful confirmation
      setTimeout(() => {
        goto('/chat');
      }, 2000);

    } catch (err: any) {
      console.error('Auth callback error:', err);
      error = err.message || 'Er is een fout opgetreden bij het bevestigen van je e-mailadres.';
    } finally {
      isLoading = false;
    }
  });
</script>

<svelte:head>
  <title>DOBbie - E-mail Bevestiging</title>
  <meta name="description" content="Bevestig je e-mailadres voor DOBbie De Online Bedrijfsarts." />
</svelte:head>

<div class="min-h-screen flex items-center justify-center bg-[#F5F2EB] p-8">
  <div class="relative max-w-md w-full bg-white p-8 md:p-10 rounded-lg shadow-lg text-center">
    
    {#if isLoading}
      <!-- Loading state -->
      <div class="space-y-4">
        <div class="w-16 h-16 mx-auto bg-[#771138] rounded-full flex items-center justify-center">
          <svg class="animate-spin h-8 w-8 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
        </div>
        <h1 class="font-serif text-[24px] font-bold text-[#771138]">E-mailadres bevestigen</h1>
        <p class="text-[#707070] text-[15px]">Een moment geduld, we bevestigen je e-mailadres...</p>
      </div>
      
    {:else if success}
      <!-- Success state -->
      <div class="space-y-4">
        <div class="w-16 h-16 mx-auto bg-green-500 rounded-full flex items-center justify-center">
          <svg class="h-8 w-8 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
          </svg>
        </div>
        <h1 class="font-serif text-[24px] font-bold text-[#771138]">Bevestiging gelukt!</h1>
        <p class="text-[#3D3D3D] text-[15px]">Je e-mailadres is succesvol bevestigd. Je wordt automatisch doorgestuurd naar DOBbie.</p>
        <div class="flex items-center justify-center space-x-2 text-[#707070] text-[14px]">
          <svg class="animate-spin h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
          <span>Doorsturen...</span>
        </div>
      </div>
      
    {:else if error}
      <!-- Error state -->
      <div class="space-y-6">
        <div class="w-16 h-16 mx-auto bg-red-500 rounded-full flex items-center justify-center">
          <svg class="h-8 w-8 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </div>
        <div>
          <h1 class="font-serif text-[24px] font-bold text-[#771138] mb-2">Bevestiging mislukt</h1>
          <p class="text-red-600 text-[15px] mb-4">{error}</p>
          <p class="text-[#707070] text-[14px]">Probeer opnieuw te registreren of neem contact met ons op als het probleem aanhoudt.</p>
        </div>
        
        <div class="space-y-3">
          <a 
            href="/register" 
            class="block w-full py-3 px-6 bg-[#771138] text-white rounded-md hover:bg-[#5A0D29] transition-colors duration-200 font-semibold text-[15px]"
          >
            Opnieuw registreren
          </a>
          <a 
            href="/login" 
            class="block w-full py-3 px-6 border border-[#771138] text-[#771138] rounded-md hover:bg-[#771138] hover:text-white transition-all duration-200 font-semibold text-[15px]"
          >
            Inloggen
          </a>
        </div>
      </div>
    {/if}
  </div>
</div>

<style>
  :global(body) {
    font-family: 'Open Sans', sans-serif;
    background-color: #F5F2EB;
  }

  .font-serif {
    font-family: 'Times New Roman', serif;
  }
</style>
