// .svelte-backup/components/layout/Footer.svelte
<!-- Footer -->
<footer class="bg-dark-gray-1 text-white py-12">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
		<div class="grid grid-cols-1 md:grid-cols-3 gap-8">
			<div>
				<div class="flex items-center mb-4">
					<svg class="h-8 w-8 text-pink-strong" fill="currentColor" viewBox="0 0 20 20">
						<path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
					</svg>
					<span class="ml-2 text-xl font-bold">DOBbie - Online Verzuimadvies</span>
				</div>
				<p class="text-gray-400 text-sm">
					Je online verzuimbuddy die 24/7 beschikbaar is voor al je vragen over gezondheid en werk. Snelle, betrouwbare en persoonlijke ondersteuning.
				</p>
			</div>
			
			<div class="md:col-span-2 grid grid-cols-2 sm:grid-cols-3 gap-8">
				<div>
					<h3 class="text-md font-semibold tracking-wider uppercase">Diensten</h3>
					<ul class="mt-4 space-y-2">
						<li><a href="/arbeidsgezondheidskundig-onderzoek" class="text-gray-400 hover:text-white transition-colors text-sm">Arbeidsgezondheidskundig Onderzoek</a></li>
						<li><a href="/verzuimbegeleiding" class="text-gray-400 hover:text-white transition-colors text-sm">Verzuimbegeleiding</a></li>
						<li><a href="/preventief-advies" class="text-gray-400 hover:text-white transition-colors text-sm">Preventief Advies</a></li>
						<li><a href="/werkplekonderzoek" class="text-gray-400 hover:text-white transition-colors text-sm">Werkplekonderzoek</a></li>
					</ul>
				</div>
				<div>
					<h3 class="text-md font-semibold tracking-wider uppercase">Voor Werkgevers</h3>
					<ul class="mt-4 space-y-2">
						<li><a href="/diensten" class="text-gray-400 hover:text-white transition-colors text-sm">Onze Diensten</a></li>
						<li><a href="/tarieven" class="text-gray-400 hover:text-white transition-colors text-sm">Tarieven</a></li>
						<li><a href="/aanmelden" class="text-gray-400 hover:text-white transition-colors text-sm">Aanmelden</a></li>
						<li><a href="/contact" class="text-gray-400 hover:text-white transition-colors text-sm">Contact</a></li>
					</ul>
				</div>
				<div>
					<h3 class="text-md font-semibold tracking-wider uppercase">Juridisch</h3>
					<ul class="mt-4 space-y-2">
						<li><a href="/privacybeleid" class="text-gray-400 hover:text-white transition-colors text-sm">Privacybeleid</a></li>
						<li><a href="/voorwaarden" class="text-gray-400 hover:text-white transition-colors text-sm">Voorwaarden</a></li>
						<li><a href="/cookiebeleid" class="text-gray-400 hover:text-white transition-colors text-sm">Cookie Beleid</a></li>
						<li><a href="/kwaliteitsverklaring" class="text-gray-400 hover:text-white transition-colors text-sm">Kwaliteitsverklaring</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="mt-12 border-t border-dark-gray-3 pt-8 flex flex-col md:flex-row justify-between items-center">
			<p class="text-gray-400 text-sm">© 2024 DOBbie - Online Verzuimadvies. Alle rechten voorbehouden.</p>
			<div class="mt-4 md:mt-0 flex space-x-6">
				<a href="#" class="text-gray-400 hover:text-pink-strong" aria-label="LinkedIn">
					<span class="sr-only">LinkedIn</span>
					<svg class="h-5 w-5" fill="currentColor" viewBox="0 0 24 24">
						<path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/>
					</svg>
				</a>

			</div>
		</div>
	</div>
</footer>

// docs/mockup/components/Footer.tsx

import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="bg-brand-light border-t border-gray-200/50 pt-16 pb-8">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mb-8">
          <div>
            <div className="flex items-center space-x-2 mb-4">
                <svg className="h-7 w-7 text-brand-dark" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fillRule="evenodd" clipRule="evenodd" d="M12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2ZM12 4C7.58172 4 4 7.58172 4 12C4 16.4183 7.58172 20 12 20C16.4183 20 20 16.4183 20 12C20 7.58172 16.4183 4 12 4ZM11 11V7H13V11H11ZM11 13H13V15H11V13Z"/>
                </svg>
                <span className="text-xl font-bold text-brand-dark font-serif">DOBbie</span>
            </div>
            <p className="text-sm text-brand-text">Uw slimme partner in verzuimadvies.</p>
          </div>
          <div>
            <h4 className="font-bold text-[#5A0D29] mb-4">Snelle Links</h4>
            <ul className="space-y-2">
              <li><a href="#waarom" className="text-sm text-brand-text hover:text-[#5A0D29]">Waarom DOBbie</a></li>
              <li><a href="#visie" className="text-sm text-brand-text hover:text-[#5A0D29]">Visie</a></li>
              <li><a href="#prijzen" className="text-sm text-brand-text hover:text-[#5A0D29]">Prijzen</a></li>
              <li><a href="#faq" className="text-sm text-brand-text hover:text-[#5A0D29]">FAQ</a></li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold text-[#5A0D29] mb-4">Contact</h4>
            <ul className="space-y-2">
              <li><a href="#" className="text-sm text-brand-text hover:text-[#5A0D29]">info@dobbie.nl</a></li>
              <li><a href="#" className="text-sm text-brand-text hover:text-[#5A0D29]">LinkedIn</a></li>
            </ul>
          </div>
           <div>
            <h4 className="font-bold text-[#5A0D29] mb-4">Legal</h4>
            <ul className="space-y-2">
              <li><a href="#" className="text-sm text-brand-text hover:text-[#5A0D29]">Privacybeleid</a></li>
              <li><a href="#" className="text-sm text-brand-text hover:text-[#5A0D29]">Algemene Voorwaarden</a></li>
            </ul>
          </div>
        </div>
        <div className="border-t border-gray-200/50 pt-6 text-center text-sm text-brand-text">
          <p>&copy; {new Date().getFullYear()} DOBbie. Alle rechten voorbehouden.</p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
